#version: "3.9"
#services:
#  xui:
#    build:
#      context: .
#      dockerfile: Dockerfile.alpha
#    image: enwaiax/x-ui
#    container_name: xui
#    restart: unless-stopped
#    network_mode: host
#    volumes:
#      - $PWD/db/:/etc/x-ui/
#      - $PWD/cert/:/root/cert/
#
version: "3.9"
services:
  xui:
    image: enwaiax/x-ui:alpha
    container_name: xui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    restart: unless-stopped
    network_mode: host
    ports:
    - 80
    - 443
    - 54321
    - 14791
    - 40778